### ISSUE TITLE
La clave para los ficheros de tests "test", no "tests"

### ISSUE THREAD

**Issue by JJ** [TDD-AY/TDD-Project#42]
Por favor, corregidla y volved a enviar el hito 8.

**Comment by yabirgb** [comment]
Hola @JJ , no tenemos claro a que te refieres. Tenemos `runner` en https://github.com/TDD-AY/TDD-Project/blob/master/qa.json#L8 y no hay ningún `runner2` en el repo, al menos la busqueda de github no dice que lo haya

**Comment by JJ** [comment]
Es que me he equivocado de repo...

**Comment by JJ** [comment]
Este es el error de vuestro repo.
