### ISSUE TITLE
Herramientas a utilizar

### ISSUE THREAD

**Issue by yabirgb** [TDD-AY/TDD-Project#5]
Hago una propuesta inicial de herramientas para cubrir los objetivos que nos proponemos en este proyecto:

- Como lenguaje principal para el proyecto propongo **python** ya que es un lenguaje que creo nos proporciona la capacidad de realizar un desarrollo rápido por las características del mismo y que a la vez cuenta con numerosas librerías que tienen cubiertas necesidades del proyecto
- Para conectar con la API de telegram propongo la utilización de [**python-telegram-bot**](https://github.com/python-telegram-bot/python-telegram-bot), por experiencia con esta API, es una de las librerías más completas y con más apoyo de la comunidad.
- Como servidor web para procesar la información que solicite el usuario del proyecto propongo la utilización de flask, porque es una herramienta ampliamente testada con un _throughput_ respetable para las dimensiones del proyecto.
- En lo respectivo a la interfaz web propongo un sitio web estático con uso de HTML/JS/CSS. También propongo la utilización de [tailwind css](https://tailwindcss.com/) como framework de css.
- Para iniciar el bot de telegram y el servidor web propongo la utilización de [supervisord](http://supervisord.org/running.html) que es una herramienta ampliamente utilizada en este campo y que proporciona herramientas de control para los distintos servicios.
- También para manejar el trafico web propongo la utlización de nginx

**Comment by aalonso99** [comment]
- Sobre el lenguaje, veo adecuado el uso de python para el bot de telegram y la librería que propones. Flask también parece suficiente dada la complejidad del proyecto.
- Para el frontend, podríamos almacenarlo en GitHub Pages y gestionarlo con Vue.js o cualquier framework similar de JS. Simplificaría el proceso y github nos ahorraría supervisar el tráfico web con nginx.

**Comment by aalonso99** [comment]
Falta por discutir también la base de datos. A priori, dado el tipo de datos que queremos almacenar (trayectorias ordenadas por días y tiempos de recorrido) podríamos usar una BD SQL.

**Comment by yabirgb** [comment]
Me parece correcto que hagamos un SPA ya que el proyecto no es tan grande y podemos simplificar el proyecto. Respecto a la base de datos veo bien que usemos Postgresql, tanto por los requisitos del proyecto como por la capacidad que tiene de tener campos JSONB

**Comment by aalonso99** [comment]
Para la configuración remota podemos usar etcd (parece contar con una buena documentación y se usa extensamente) y para el logging podemos probar con LogDNA que tiene una tarifa básica gratuita.

**Comment by JJ** [comment]
Siempre debéis cerrar los issues con un commit, aunque sean issues de discusión como este. Un isuse de discusión dará lugar a un documento, y al añadir o cerrar el documento podéis cerrar el issue con un commit. Con la nueva versión os va a seguri dando error este y el 1 hasta que no los cerréis con un commit.
